# Generated by Django 3.1.5 on 2021-01-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210127_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='shipDate',
            field=models.CharField(max_length=30),
        ),
    ]
